# Generated by Django 5.0.7 on 2025-01-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trainer', max_length=100)),
                ('username', models.CharField(default='default_username', max_length=60)),
                ('password', models.CharField(default='defaultpassword', max_length=50)),
                ('dob', models.DateField(default='2000-01-01')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/')),
                ('qualification', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField(default='2000-01-01')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/')),
            ],
        ),
    ]
