# Generated by Django 5.1.4 on 2025-01-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0002_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('descrption', models.CharField(max_length=100)),
            ],
        ),
    ]
