# Generated by Django 5.1.4 on 2025-01-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Name',
            field=models.CharField(default='hjgjh', max_length=25),
            preserve_default=False,
        ),
    ]
