# Generated by Django 5.1.4 on 2025-01-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_remove_trainerprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Type',
            field=models.CharField(default='hjjj', max_length=50),
            preserve_default=False,
        ),
    ]
