# Generated by Django 5.1.4 on 2025-01-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0006_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
