# Generated by Django 5.1.4 on 2025-01-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0008_userprofile_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplements/images/')),
            ],
            options={
                'verbose_name': 'Supplement',
                'verbose_name_plural': 'Supplements',
                'ordering': ['name'],
            },
        ),
    ]
