# Generated by Django 5.1.4 on 2025-01-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0009_supplement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplement',
            options={},
        ),
    ]
