# Generated by Django 5.1.4 on 2025-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0010_alter_supplement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
