# Generated by Django 5.1.6 on 2025-02-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0011_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='fitapp.trainerprofile'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.supplement')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.TextField(default='🍳 Scrambled Eggs, 🥑 Avocado Toast, 🍓 Fresh Berries')),
                ('lunch', models.TextField(default='🥗 Grilled Chicken Salad, 🍚 Quinoa, 🥕 Steamed Broccoli')),
                ('dinner', models.TextField(default='🍣 Baked Salmon, 🥔 Mashed Sweet Potatoes, 🥦 Sautéed Spinach')),
                ('snacks', models.TextField(default='🍌 Banana, 🥜 Almonds, 🍏 Apple Slices with Peanut Butter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWithQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.supplement')),
            ],
        ),
        migrations.CreateModel(
            name='BuyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=7, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.userprofile')),
                ('supplements', models.ManyToManyField(blank=True, to='fitapp.productwithquantity')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='session_videos/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.plan')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='trainer_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets', models.IntegerField(default=3)),
                ('repetitions', models.IntegerField(default=5)),
                ('duration', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.userprofile')),
            ],
        ),
    ]
